### PR TITLE
Move to cargo-generate template

### PR DESCRIPTION
**Pull request by riverar**
Switches out the crate for a new cargo-generate template with the same goals in mind. Also now generates metadata for Microsoft.WindowsAppSDK.Foundation and Microsoft.WindowsAppSDK.WinUI interop types, eliminating the need to manually write and maintain that code.

### CODE REVIEW

**Comment by Alovchin91** [comment]
Hmm, looks like it's time to make sure `cargo-generate` works on Windows ARM64 😅

**Review by kennykerr — APPROVED** [review]

**Comment by riverar** [comment]
@Alovchin91 Will try this on arm64 tonight, I don't expect any issues although I'm not sure if there's a Windows App SDK runtime for ARM64... hmmmm.

// TODO
Need to rename this branch after merge to `experimental`, change the default branch in the repro to `experimental`, then after WAS 1.0 goes out the door, we can spin up `stable` and `preview`.

**Comment by Alovchin91** [comment]
> I'm not sure if there's a Windows App SDK runtime for ARM64... hmmmm.

There is and to my knowledge always has been (thankfully!), though there is no installer for it (yet?). So it's just a set of MSIX files which I guess doesn't really matter for this crate 🙂

I think my biggest concern with cargo-generate is vendored-openssl which I _think_ didn't compile for me in the past, but I'm not even sure it's an option for Windows anyway (given https://github.com/rust-lang/rustup/blob/master/ci/run.bash#L13) 🤷‍♂️

**Comment by riverar** [comment]
image

We're good on WOA.

Am still contemplating whether or not we continue to use `cargo-generate` due to the high _cost_ (deps) for little benefit. Decisions, decisions...

**Comment by kennykerr** [comment]
Rockstar @riverar showing off WinUI/WinAppSDK with Rust on ARM64. 

@jonwis @BenJKuhn @rylev @clarkezone @mikehillberg

**Review by kennykerr — APPROVED** [review]

**Pull request merged**
